volcano-sh/website

assets/css/custom.css, config/_default/menus.toml, themes/academic/data/themes/default.toml
Updated text color of menu and content width of documentation page.  
NA
=> Updated menu text color, documentation content width

config/_default/menus.toml, content/en/author/volcano/_index.md, content/en/docs/_index.md, content/en/docs/deployment.md, content/en/home/home_slider.md
=> Publish the website with some minor changes like repo link update

content/en/blog/Quick-Start-Volcano.md
=> Updated Quick start Guide

config/_default/menus.toml, content/en/docs/deployment.md
https://tech-preview.volcano.sh/
=> Publish Changes to main website

config/_default/menus.toml, content/en/docs/getting-started.md
https://github.com/volcano-sh/volcano/issues/347
=> Add Getting started doc from releases

static/_redirects, static/golang/volcano.html
Support go get in volcano.sh website
For #18
=> Support go get

config/_default/config.toml
=> update google analysis tracing id

.github/workflows/fossa.yml
Fixes https://github.com/volcano-sh/volcano/issues/936
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> FOSSA scanning added to the website repo

config/_default/menus.toml
- [X ] The commit message follows our guidelines
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A ] Docs have been added / updated (for bug fixes / features)
Changing slack to the CNCF slack channel
=> Changing to CNCF slack channel

doc/concepts/vcjob.md
=> add vcjob doc

doc/concepts/priorityClassName.md
=> add priorityClassName doc

doc/concepts/podgroup.md
=> add podgroup doc

doc/concepts/queue.md
=> add queue doc

assets/css/custom.css, config/_default/menus.toml, content/en/home/home_slider.md, layouts/partials/blog_author.html, themes/academic/layouts/partials/css/academic.css, themes/academic/layouts/partials/docs_layout.html, themes/academic/layouts/partials/navbar.html, themes/academic/layouts/partials/widget_page.html, themes/academic/layouts/partials/widgets/slider.html
=> change navbar and somethings

content/en/docs/CLI.md, content/en/docs/contribution.md, content/en/home/about.md, content/zh/docs/CLI.md, content/zh/docs/architecture.md, content/zh/docs/contribution.md, content/zh/docs/queue.md, content/zh/docs/tutorials.md, content/zh/home/posts.md, content/zh/home/required.md, themes/academic/layouts/partials/widgets/pages.html
Signed-off-by: 路文静 <1098426275@qq.com>
=> complete zh

config/_default/languages.toml, content/en/docs/vcjob.md, content/zh/docs/_index.md, content/zh/docs/architecture.md, content/zh/docs/contribution.md, content/zh/docs/installation.md, content/zh/docs/queue.md, content/zh/docs/tutorials.md
=> fix some bugs

OWNERS
=> request approver role

config/_default/languages.toml, content/zh/home/about.md, content/zh/home/talks.md, content/zh/talk/_index.md, themes/academic/i18n/zh.yaml, themes/academic/layouts/partials/widgets/pages.html
=> update some expressions

content/zh/docs/installation.md
=> Change error link of Chinese installation document

content/zh/docs/contribution.md
=> Update contribution document error anchor

content/zh/docs/contribution.md, content/zh/docs/installation.md
Signed-off-by: aimuz <mr.imuz@gmail.com>
=> fix Wrong link

doc/concepts/vcjob.md
* **What kind of change does this PR introduce?** (docs update)
=> Fixed vcjob.md

content/en/docs/contribution.md, content/zh/docs/contribution.md
Fix docs spell issue.
Docs update.
=> Fix spell issue

content/en/docs/contribution.md, content/zh/docs/contribution.md
=> Revert "Docs: fix dead links"

content/en/docs/membership.md, content/zh/docs/membership.md
/kind cleanup
The original right meue is not aligned.
=> Docs: format align for membership

content/en/docs/installation.md, content/zh/docs/installation.md
=> Docs: add right menu for installation

content/en/docs/contribution.md
/kind cleanup
The original right bar is not aligned.
=> Docs: format right bar

content/en/docs/contribution.md, content/zh/docs/contribution.md
=> Docs: fix dead links

content/en/docs/cli.md, content/zh/docs/cli.md
`--` in common conent shows as `-`, may mislead users, remove them.
=> Docs: update cli doc

content/en/docs/architecture.md, content/zh/docs/architecture.md
Title is as big as content, which is bad.
=> Docs: update architecture format

content/en/blog/Quick-Start-Volcano.md, content/en/blog/kube-batch-customers.md, content/en/blog/kube-batch-startup.md, content/en/docs/_index.md, content/en/docs/architecture.md, content/en/docs/cli.md, content/en/docs/contribution.md, content/en/docs/installation.md, content/en/docs/membership.md, content/en/docs/podgroup.md, content/en/docs/queue.md, content/en/docs/schduler_introduction.md, content/en/docs/tutorials.md, content/en/docs/vcjob.md, content/en/home/home_slider.md, content/en/home/required.md, content/en/talk/kubecon-barcelona-2019/index.md, content/zh/docs/vcjob.md, content/zh/home/home_slider.md, layouts/partials/footer_section.html
=> english version format

content/en/home/required.md, content/en/home/supporter.md, content/zh/home/required.md, content/zh/home/supporter.md, layouts/partials/footer_section.html
=> fix supporter and frameworks

layouts/partials/footer_section.html
=> footer fix

content/en/docs/tutorials.md, content/zh/docs/tutorials.md
=> fix samples bug

config/_default/config.toml, config/_default/languages.toml
=> update v1.0 to v1.x

content/zh/docs/contribution.md
我们不仅估计大家贡献代码，也非常欢迎大家提交 issue。 issue 需要被提交到 Volcano 的对应子仓库中。
应该为
我们不仅鼓励大家贡献代码，也非常欢迎大家提交 issue。 issue 需要被提交到 Volcano 的对应子仓库中。
文档书写错误
=> Wrong doc word in volcano zh doc

static/_redirects, static/golang/volcano.html
Signed-off-by: Thor-wl <1187526662@qq.com>
=> add redircet for api repo

static/_redirects, static/golang/api.html, static/golang/volcano.html
Signed-off-by: Thor-wl <1187526662@qq.com>
=> set apis redirect

content/en/docs/flink_on_volcano.md, content/en/docs/installation.md, content/en/docs/kubeflow_on_volcano.md, content/en/docs/mindspore_on_volcano.md, content/en/docs/mpi_on_volcano.md, content/en/docs/plugins.md, content/en/docs/pp_on_volcano.md, content/en/docs/spark_on_volcano.md, content/en/docs/tf_on_volcano.md, content/en/docs/vcjob.md, content/en/home/required.md, content/zh/blog/kube-batch-customers.md, content/zh/docs/flink_on_volcano.md, content/zh/docs/kubeflow_on_volcano.md, content/zh/docs/mindspore_on_volcano.md, content/zh/docs/mpi_on_volcano.md, content/zh/docs/plugins.md, content/zh/docs/podgroup.md, content/zh/docs/pp_on_volcano.md, content/zh/docs/spark_on_volcano.md, content/zh/docs/tf_on_volcano.md, content/zh/docs/tutorials.md, content/zh/docs/vcjob.md, content/zh/home/required.md, doc/concepts/podgroup.md, doc/concepts/vcjob.md
Signed-off-by: Thor-wl <13164644535@163.com>
=> fix some bugs about spelling and unless reference

content/en/blog/Quick-Start-Volcano.md, content/en/blog/kube-batch-startup.md, content/en/blog/leinao-en.md, content/en/blog/paddlepaddle-en.md, content/en/blog/ruitian-en.md, content/zh/blog/Quick-Start-Volcano.md, content/zh/blog/kube-batch-startup.md, content/zh/blog/leinao-cloud-os.md, content/zh/blog/paddlepaddle.md, content/zh/blog/ruitian.md
Signed-off-by: Thor-wl <13164644535@163.com>
=> fix the style of blogs

content/en/blog/1.4 release-en.md, content/zh/blog/1.4 release.md
Signed-off-by: Jessica-wang-0816 <361165796@qq.com>
=> add blog 1.4 release

themes/academic/layouts/partials/css/academic.css
resolve https://github.com/volcano-sh/website/issues/129
=> update search icon

layouts/partials/footer_section.html
resolve https://github.com/volcano-sh/website/issues/127
=> update copyright year

themes/academic/layouts/partials/navbar.html
resolve https://github.com/volcano-sh/website/issues/135
/kind bug
/kind design
=> fix version dropdown

themes/academic/layouts/partials/css/academic.css, themes/academic/layouts/partials/footer_container.html
resolve https://github.com/volcano-sh/website/issues/137
/kind bug
/kind design
=> fix footer on mobile

assets/css/custom.css, layouts/partials/widgets/featured.html, layouts/partials/widgets/supporter.html
resolve https://github.com/volcano-sh/website/issues/143
=> update cards sections

config/_default/languages.toml, config/_default/menus.toml, themes/academic/layouts/partials/css/academic.css, themes/academic/layouts/partials/navbar.html
resolve https://github.com/volcano-sh/website/issues/141
/kind design
=> update search block on mobile

config/_default/languages.toml, config/_default/menus.toml, layouts/_default/list.html, layouts/partials/footer_section.html, layouts/partials/page_header.html, themes/academic/layouts/partials/li_compact.html, themes/academic/layouts/partials/li_compact_talk.html
resolve https://github.com/volcano-sh/website/issues/145
=> Accessibility add alt to images

themes/academic/layouts/partials/css/academic.css
resolve https://github.com/volcano-sh/website/issues/148
/kind bug
/kind design
=> fix dropdown menu on mobile

layouts/partials/widgets/featured.html
resolve https://github.com/volcano-sh/website/issues/147
/kind design
=> update cards block on tablet

themes/academic/layouts/partials/widgets/about.html
resolve https://github.com/volcano-sh/website/issues/151
=> Accessibility update links

themes/academic/layouts/partials/widgets/about.html
resolve https://github.com/volcano-sh/website/issues/153
=> Accessibility add alt to img

assets/css/custom.css, themes/academic/layouts/partials/widgets/slider.html
resolve https://github.com/volcano-sh/website/issues/157
/kind design
=> fix home slider on mobile

themes/academic/layouts/partials/navbar.html
resolve https://github.com/volcano-sh/website/issues/155
=> Accessibility add link name

themes/academic/layouts/partials/widgets/slider.html
resolve https://github.com/volcano-sh/website/issues/159
=> fix slider item on tablet & mobile

themes/academic/layouts/partials/share.html
resolve https://github.com/volcano-sh/website/issues/161
=> Accessibility update social icons

layouts/partials/blog_metadata.html
resolve https://github.com/volcano-sh/website/issues/163
=> Accessibility add alt to image

content/en/docs/installation.md, content/zh/docs/installation.md
Add note for specific version volcano installation
docs update
For users who want to install specific version volcano.
Closes: https://github.com/volcano-sh/volcano/issues/2093
=> Add note for specific version volcano installation (Install with YAML files)

layouts/partials/header.html
resolve https://github.com/volcano-sh/website/issues/178
=> update & add favicons

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/180
=> fix tag label

assets/css/custom.css, layouts/partials/widgets/featured.html, themes/academic/layouts/partials/css/academic.css
resolve https://github.com/volcano-sh/website/issues/182
=> update cards on mobile UI

themes/academic/layouts/partials/css/academic.css
resolve https://github.com/volcano-sh/website/issues/184
=> fix toggle on mobile

assets/css/custom.css, layouts/_default/list.html, themes/academic/layouts/partials/li_compact.html, themes/academic/layouts/partials/page_metadata.html
resolve https://github.com/volcano-sh/website/issues/186
=> fix Recent Posts block on mobile

assets/css/custom.css, themes/academic/layouts/partials/li_compact.html
resolve https://github.com/volcano-sh/website/issues/188
=> fix Recent Posts block on tablet

assets/css/custom.css, themes/academic/layouts/partials/widgets/slider.html
resolve https://github.com/volcano-sh/website/issues/191
=> fix hero image on mobile

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/193
=> update hero slider on mobile

assets/css/custom.css, layouts/_default/single.html
resolve https://github.com/volcano-sh/website/issues/195
=> fix blog related links

assets/css/custom.css, layouts/partials/blog_author.html
resolve https://github.com/volcano-sh/website/issues/197
=> fix blog card on tablet

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/199
=> fix table on mobile

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/202
=> fix long link goes off screen

themes/academic/layouts/partials/li_compact_talk.html, themes/academic/layouts/section/talk.html
resolve https://github.com/volcano-sh/website/issues/204
=> update talk page

layouts/_default/list.html
resolve https://github.com/volcano-sh/website/issues/206
=> fix blog on tablet

themes/academic/layouts/shortcodes/figure.html
resolve https://github.com/volcano-sh/website/issues/208
=> add alt to docs images

themes/academic/layouts/partials/css/academic.css
resolve https://github.com/volcano-sh/website/issues/211
=> fix search result scroll

layouts/partials/footer_section.html
resolve https://github.com/volcano-sh/website/issues/219
=> add link to Cloud Native Computing Foundation

layouts/partials/footer_section.html
resolve https://github.com/volcano-sh/website/issues/221
=> add link to Trademark Usage

netlify.toml
=> revert & update hugo

README.md
resolve https://github.com/volcano-sh/website/issues/226
=> update readme hugo install

content/en/home/supporter.md
resolve https://github.com/volcano-sh/website/issues/228
=> update supporter links

themes/academic/layouts/partials/docs_sidebar.html
resolve https://github.com/volcano-sh/website/issues/232
=> update docs arrow (ui)

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/236
=> fix user page

layouts/partials/widgets/featured.html
resolve https://github.com/volcano-sh/website/issues/240
=> add css cursor on cards

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/244
=> fix border on tablet

assets/css/custom.css, content/en/blog/Quick-Start-Volcano.md, layouts/_default/list.html, layouts/partials/blog_metadata.html, static/img/icon_user.svg, themes/academic/layouts/partials/li_compact.html
resolve https://github.com/volcano-sh/website/issues/250
=> update user icon to svg

README.md
* **Repaired `How to contributing` in README.md**
* **What kind of change does this PR introduce?** (documentation)
* **It repaired the link `How to contributing` in [README.md](https://github.com/volcano-sh/website/blob/master/README.md) and redirect it to the [contribute.md](https://github.com/volcano-sh/volcano/blob/master/contribute.md)**:
* **Fixes #254 **:
=> repaired How to contributing link

assets/css/custom.css, layouts/_default/list.html
resolve https://github.com/volcano-sh/website/issues/264
=> fix blog card on mobile

content/en/blog/Quick-Start-Volcano.md, content/zh/blog/Quick-Start-Volcano.md, themes/academic/layouts/shortcodes/gdocs.html
resolve https://github.com/volcano-sh/website/issues/266
=> Accessibility add iframe title

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/276
=> refactor css

OWNERS
resolve https://github.com/volcano-sh/community/issues/32
=> add arhell as a reviewers

content/en/docs/installation.md, content/zh/docs/installation.md, doc/quickstart.md
=> Fix website installation

assets/js/custom.js
resolve https://github.com/volcano-sh/website/issues/278
=> refactor js

.gitignore
resolve https://github.com/volcano-sh/website/issues/288
=> add .hugo_build.lock to gitignore

content/zh/blog/Volcano-1.7.0-release.md
Volcano 1.7.0 has been officially released, the article mainly introduces the new features and functions of this version
=> add Volcano v1.7.0 release blog for zh

content/en/docs/tf_on_volcano.md, content/zh/docs/tf_on_volcano.md
/kind bug
tensorflow demo wrong.
Fix: https://github.com/volcano-sh/volcano/issues/2653
=> update tf demo

content/en/blog/ING_case-en.md, content/en/blog/Volcano-1.7.0-release-en.md
Update English blog content
- ING Bank: How Volcano Empowers Their Big Data Analytics Platform
- Volcano 1.7.0 Available Now
=> Update English blog (ING bank time, version 1.7.0 released)

layouts/partials/footer_section.html
resolve https://github.com/volcano-sh/website/issues/295
=> update current year

layouts/partials/blog_metadata.html
/kind bug
resolve https://github.com/volcano-sh/website/issues/302
=> fix date format

content/en/docs/plugins.md, content/zh/blog/ING_case.md, content/zh/docs/plugins.md
=> fix DRF typo

themes/academic/layouts/partials/navbar.html
resolve https://github.com/volcano-sh/website/issues/308
=> Accessibility update search bar

themes/academic/layouts/partials/css/academic.css
https://github.com/volcano-sh/website/issues/311
https://github.com/volcano-sh/website/issues/311
=> code section use mono font

content/en/blog/Volcano-1.8.2-release.md, content/zh/blog/Volcano-1.8.2-release.md
helm repo add volcano-sh https://volcano-sh.github.io/helm-chart
Error: looks like "https://volcano-sh.github.io/helm-chart" is not a valid chart repository or cannot be reached: failed to fetch https://volcano-sh.github.io/helm-chart/index.yaml : 404 Not Found
helm chart repo is https://volcano-sh.github.io/helm-charts ，not https://volcano-sh.github.io/helm-chart
=> doc: fix installation cmd in release 1.8.2 blog

config/_default/config.toml, layouts/partials/footer_section.html
resolve https://github.com/volcano-sh/website/issues/325
=> update footer date

content/en/docs/vcjob.md
Documentation update.
Fixes the broken schedulerName selection.
No issue was created before.
=> doc: fix schedulerName typo description

content/en/docs/queue.md
Queue English document formatting error, fix it
Related issue #330
=> fix english queue doc

assets/css/custom.css
resolve https://github.com/volcano-sh/website/issues/339
=> fix dropdown styles

content/en/blog/Volcano-1.11.0-release.md, content/zh/blog/Volcano-1.11.0-release.md
=> Add v1.11.0 blog

assets/css/custom.css, themes/academic/layouts/partials/navbar.html
resolve https://github.com/volcano-sh/website/issues/355
=> fix redundant space of dropdown

themes/academic/layouts/partials/widgets/about.html
Fixes https://github.com/volcano-sh/website/issues/354
=> Extra space removal

content/en/docs/contribution.md, themes/academic/layouts/partials/widgets/about.html
/kind bug
/kind cleanup
This PR
- add `volcano` channel link on contribution page.
- fixes line height on main page
Fixes #366 
Fixes #362
=> fix: slack link on contribution page

config/_default/languages.toml, config/_default/menus.toml, themes/academic/data/assets.toml
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)  
* **What this PR does / why we need it**:  
This PR updates the old Twitter bird logo to the new X logo in the UI. Additionally, it updates the Font Awesome CDN version to support the latest icons.
* **Which issue(s) this PR fixes**:  
- Fixes **#361**
=> Updated the Font Awesome CDN version and twitter logo

content/en/blog/how-volcano-boosts-distributed-training-and-inference-performance.md
=> Add kubecon blog

content/zh/blog/Volcano-1.11.0-release.md
&nbsp;&nbsp;Bug fix
&nbsp;&nbsp;The link and subsequent characters are improperly concatenated, leading to inaccurate navigation to the designated page upon click.
&nbsp;&nbsp; After fix, the link now correctly navigates to the designated page upon user interaction.
=> Fix link jump error

content/en/docs/gpu_virtualization.md, content/en/docs/tutorials.md, content/en/docs/unified_scheduling.md, content/zh/docs/gpu_virtualization.md, content/zh/docs/tutorials.md, content/zh/docs/unified_scheduling.md, themes/academic/layouts/partials/css/academic.css
1. Update tutorials, add a tutorial on specifying minmember in Deployment
2. Add DRA configuration tutorial in unified scheduling
3. Add vgpu doc
4. Update title style
v1.12 is about to be released, need to update the documentation
NONE
=> Update tutorials/ Add DRA/ Add vGPU document

content/en/docs/network_topology_aware_scheduling.md, content/zh/docs/network_topology_aware_scheduling.md
v1.12 will be relaesed soon, need to update network topology aware scheduling doc
NONE
=> Update network topology aware scheduling doc

content/en/docs/tutorials.md, content/zh/docs/tutorials.md
Fix the deployment examples in tutorals.
ralated: #2731
=> fix: deployment examples in tutorials

content/en/docs/queue.md, content/en/docs/v1-11-0/queue.md, content/en/docs/v1-12-0/queue.md
The original queue page can't access hierarchical_queue through link.
=> feat: fix 404 page of hierarchical_queue

content/en/docs/multi_cluster_scheduling.md, content/en/docs/v1-11-0/multi_cluster_scheduling.md, content/en/docs/v1-12-0/multi_cluster_scheduling.md, content/zh/docs/multi_cluster_scheduling.md, content/zh/docs/v1-11-0/multi_cluster_scheduling.md, content/zh/docs/v1-12-0/multi_cluster_scheduling.md
There are some misrepresentations in the current documentation for multi-cluster scheduling that need to be updated
NONE
=> Change the discription of background of multi cluster scheduling
